# Generated by Django 3.2.7 on 2021-09-15 21:57

from django.db import migrations, models
import policy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodily_injury_liability', models.BooleanField(default=False)),
                ('personal_injury_protection', models.BooleanField(default=False)),
                ('property_damage_liability', models.BooleanField(default=False)),
                ('collision', models.BooleanField(default=False)),
                ('comprehensive', models.BooleanField(default=False)),
                ('premium', models.IntegerField(validators=[policy.models.validate_premium])),
                ('vehicle_segment', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=200)),
                ('fuel', models.CharField(choices=[('CNG', 'CNG'), ('Petrol', 'Petrol'), ('Diesel', 'Diesel')], max_length=200)),
                ('date_of_policy', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
