# Generated by Django 3.2.7 on 2021-09-16 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_policy_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='date_of_policy',
        ),
        migrations.AddField(
            model_name='policy',
            name='date_of_purchase',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
