# Generated by Django 3.2.7 on 2021-09-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_auto_20210916_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='bodily_injury_liability',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='policy',
            name='collision',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='policy',
            name='comprehensive',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='policy',
            name='personal_injury_protection',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='policy',
            name='property_damage_liability',
            field=models.BooleanField(),
        ),
    ]
